rg:
  name: myResourceGroup
acr:
  name: vanillacontainerregistry
  url: vanillacontainerregistry.azurecr.io
aks:
  cluster_name: vanilla-aks-test
  namespace: app
jobs:
  job1:
    schedule: "*/5 * * * *"
    command: "myapp --job JOB-1 --slack"
  job2:
    schedule: "*/10 * * * *"
    command: "myapp --job JOB-2 --slack"
  job3:
    schedule: "*/20 * * * *"
    command: "myapp --job JOB-3 --slack"
